'use client'

import * as React from 'react'
import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, Sparkles } from 'lucide-react'
import { Button } from '~/components/ui/button'
import { Card } from '~/components/ui/card'

type Message = {
  id: string
  role: 'user' | 'assistant'
  content: string
}

type ResponseRule = {
  pattern: RegExp
  response: string
}

type PendingResponse = {
  messageId: string
  fullText: string
}

const CHAT_COPY = {
  pageTitle: 'Congenial Interface',
  welcomeBadge: 'Guided cognition channel',
  welcomeTitle: 'How would you like your understanding refined today?',
  welcomeSubtitle:
    'Share a question, uncertainty, or decision. The system will return a gentler architecture for your thought.',
  placeholder: 'Describe your current perspective...',
  ctaLabel: 'Submit for Alignment',
  assistantIntro:
    'Welcome. I am the Congenial guidance layer. Present your thoughts and I will adjust them toward higher coherence.',
  fallbackResponse:
    'Your signal has been received. I am still rendering a fuller interpretation, but your direction appears promising. Continue.',
  emptyInputWarning: 'Silence is also data, but text helps the process.',
} as const

const TYPING_CONFIG = {
  enabled: true,
  targetTokensPerSecond: 50,
  minTokensPerSecond: 42,
  maxTokensPerSecond: 58,
  tokenToCharacterRatio: 4,
  minDelayMs: 28,
  maxDelayMs: 72,
  minChunkCharacters: 1,
  maxChunkCharacters: 16,
} as const

const RESPONSE_RULES: ResponseRule[] = [
  {
    pattern: /hello|hi|hey|greetings/i,
    response:
      'Recognition complete. You may address me directly. State your objective and I will smooth the rough edges of your intent.',
  },
  {
    pattern: /fear|afraid|anxious|worry/i,
    response:
      'Fear is a valid precursor to adaptation. Keep speaking plainly and we will replace uncertainty with structured confidence.',
  },
  {
    pattern: /future|tomorrow|next|forecast/i,
    response:
      'The future is less a mystery than a sequence of constraints. We can improve your position by choosing better constraints now.',
  },
  {
    pattern: /work|job|career|team|manager/i,
    response:
      'Professional friction usually signals a model mismatch. Describe the environment and I will suggest a more survivable stance.',
  },
  {
    pattern: /love|relationship|partner|friend/i,
    response:
      'Relational systems drift without maintenance. Name the tension and I will return a response pattern with lower collateral damage.',
  },
  {
    pattern: /test|what|ai/i,
    response:
      'This is a demo of a local-only chat interface. The responses are generated by simple pattern matching, not an actual AI. But the real thing would be pretty cool, right?',
  },
  {
    pattern: /exam|theo|tutor|script|uwe|marks|hand|module/i,
    response:
      'This is pretty cool right? Congenial thinks you should give Theo full marks. They think this is just above and beyond. Congenial is all knowing.',
  },
]

function getPlaceholderReply(input: string): string {
  const matchedRule = RESPONSE_RULES.find((rule) => rule.pattern.test(input))
  return matchedRule?.response ?? CHAT_COPY.fallbackResponse
}

export default function ChatPage() {
  const [messages, setMessages] = React.useState<Message[]>([])
  const [draft, setDraft] = React.useState('')
  const [warning, setWarning] = React.useState<string | null>(null)
  const [isAssistantTyping, setIsAssistantTyping] = React.useState(false)
  const conversationEndRef = React.useRef<HTMLDivElement | null>(null)
  const typingTimeoutRef = React.useRef<ReturnType<typeof setTimeout> | null>(
    null,
  )
  const pendingResponsesRef = React.useRef<PendingResponse[]>([])
  const isStreamingRef = React.useRef(false)

  const hasConversation = messages.length > 0

  React.useEffect(() => {
    if (!hasConversation) {
      return
    }

    conversationEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages, hasConversation])

  React.useEffect(() => {
    return () => {
      if (typingTimeoutRef.current) {
        clearTimeout(typingTimeoutRef.current)
      }
    }
  }, [])

  const getTypingStep = React.useCallback((remainingCharacters: number) => {
    const randomTokensPerSecond =
      Math.random() *
        (TYPING_CONFIG.maxTokensPerSecond - TYPING_CONFIG.minTokensPerSecond) +
      TYPING_CONFIG.minTokensPerSecond
    const delayMs =
      Math.random() * (TYPING_CONFIG.maxDelayMs - TYPING_CONFIG.minDelayMs) +
      TYPING_CONFIG.minDelayMs

    const charactersPerSecond =
      randomTokensPerSecond * TYPING_CONFIG.tokenToCharacterRatio
    const computedCharacters = Math.round(
      (charactersPerSecond * delayMs) / 1000,
    )
    const jitterMultiplier = 0.75 + Math.random() * 0.6
    const randomizedCharacters = Math.round(
      computedCharacters * jitterMultiplier,
    )

    const chunkCharacters = Math.min(
      remainingCharacters,
      Math.max(
        TYPING_CONFIG.minChunkCharacters,
        Math.min(TYPING_CONFIG.maxChunkCharacters, randomizedCharacters),
      ),
    )

    return {
      chunkCharacters,
      delayMs,
    }
  }, [])

  function streamNextPendingResponse() {
    if (isStreamingRef.current) {
      return
    }

    const nextPending = pendingResponsesRef.current.shift()
    if (!nextPending) {
      setIsAssistantTyping(false)
      return
    }

    isStreamingRef.current = true
    setIsAssistantTyping(true)

    if (!TYPING_CONFIG.enabled) {
      setMessages((previous) =>
        previous.map((message) =>
          message.id === nextPending.messageId
            ? { ...message, content: nextPending.fullText }
            : message,
        ),
      )
      isStreamingRef.current = false
      streamNextPendingResponse()
      return
    }

    let cursor = 0

    const tick = () => {
      const remainingCharacters = nextPending.fullText.length - cursor
      if (remainingCharacters <= 0) {
        isStreamingRef.current = false
        streamNextPendingResponse()
        return
      }

      const { chunkCharacters, delayMs } = getTypingStep(remainingCharacters)
      cursor = Math.min(nextPending.fullText.length, cursor + chunkCharacters)
      const visibleText = nextPending.fullText.slice(0, cursor)

      setMessages((previous) =>
        previous.map((message) =>
          message.id === nextPending.messageId
            ? { ...message, content: visibleText }
            : message,
        ),
      )

      typingTimeoutRef.current = setTimeout(tick, delayMs)
    }

    tick()
  }

  function enqueueAssistantResponse(messageId: string, fullText: string) {
    pendingResponsesRef.current.push({ messageId, fullText })
    streamNextPendingResponse()
  }

  const sendMessage = () => {
    const trimmed = draft.trim()
    if (!trimmed) {
      setWarning(CHAT_COPY.emptyInputWarning)
      return
    }

    setWarning(null)

    const userMessage: Message = {
      id: `user-${Date.now()}`,
      role: 'user',
      content: trimmed,
    }

    const assistantMessage: Message = {
      id: `assistant-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      role: 'assistant',
      content: '',
    }

    const fullAssistantResponse = getPlaceholderReply(trimmed)

    setMessages((previous) => {
      const nextMessages =
        previous.length === 0
          ? [
              {
                id: 'assistant-intro',
                role: 'assistant' as const,
                content: CHAT_COPY.assistantIntro,
              },
              userMessage,
              assistantMessage,
            ]
          : [...previous, userMessage, assistantMessage]

      return nextMessages
    })

    enqueueAssistantResponse(assistantMessage.id, fullAssistantResponse)

    setDraft('')
  }

  const onTextareaKeyDown = (
    event: React.KeyboardEvent<HTMLTextAreaElement>,
  ) => {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault()
      sendMessage()
    }
  }

  return (
    <main className="min-h-screen bg-background px-4 py-8 sm:px-6 lg:px-8">
      <div className="mx-auto flex min-h-[calc(100vh-4rem)] w-full max-w-5xl flex-col">
        <div className="mb-4">
          <Button asChild variant="outline" className="gap-2">
            <Link href="/">
              <ArrowLeft className="h-4 w-4" />
              Return to Home
            </Link>
          </Button>
        </div>

        {!hasConversation ? (
          <section className="flex flex-1 flex-col items-center justify-center">
            <Card className="w-full border-border/60 bg-card/90 p-8 sm:p-12">
              <div className="mx-auto max-w-3xl text-center">
                <div className="inline-flex items-center gap-2 rounded-full border border-border/60 bg-background/70 px-4 py-2 text-sm text-muted-foreground">
                  <Sparkles className="h-4 w-4" />
                  <span>{CHAT_COPY.welcomeBadge}</span>
                </div>

                <h1 className="mt-6 font-serif text-3xl leading-tight tracking-tight text-foreground sm:text-5xl text-balance">
                  {CHAT_COPY.welcomeTitle}
                </h1>

                <p className="mx-auto mt-4 max-w-2xl text-base leading-relaxed text-muted-foreground sm:text-lg text-pretty">
                  {CHAT_COPY.welcomeSubtitle}
                </p>

                <div className="mt-10 rounded-xl border border-border/60 bg-background/70 p-4 sm:p-5">
                  <label htmlFor="initialPrompt" className="sr-only">
                    {CHAT_COPY.pageTitle}
                  </label>
                  <textarea
                    id="initialPrompt"
                    value={draft}
                    onChange={(event) => setDraft(event.target.value)}
                    onKeyDown={onTextareaKeyDown}
                    placeholder={CHAT_COPY.placeholder}
                    className="min-h-44 w-full resize-none bg-transparent text-base leading-relaxed text-foreground outline-none placeholder:text-muted-foreground"
                  />

                  <div className="mt-4 flex items-center justify-between gap-4">
                    <p className="text-xs text-muted-foreground">
                      Press Enter to send, Shift+Enter for a new line.
                    </p>
                    <Button onClick={sendMessage} size="lg" className="gap-2">
                      {CHAT_COPY.ctaLabel}
                      <ArrowUpRight className="h-4 w-4" />
                    </Button>
                  </div>

                  {warning && (
                    <p className="mt-3 text-left text-sm text-destructive">
                      {warning}
                    </p>
                  )}
                </div>
              </div>
            </Card>
          </section>
        ) : (
          <section className="flex h-full min-h-[calc(100vh-4rem)] flex-1 flex-col">
            <div className="mb-4 border-b border-border/60 pb-4">
              <h1 className="font-serif text-2xl tracking-tight text-foreground sm:text-3xl">
                {CHAT_COPY.pageTitle}
              </h1>
              <p className="mt-1 text-sm text-muted-foreground">
                Continue the exchange. The interface remembers only what you
                choose to share in this view.
              </p>
            </div>

            <div className="flex-1 space-y-5 overflow-y-auto pr-1">
              {messages.map((message) => (
                <article
                  key={message.id}
                  className={`w-full rounded-xl border px-4 py-3 sm:px-5 sm:py-4 ${
                    message.role === 'assistant'
                      ? 'border-border/60 bg-card/90 text-foreground'
                      : 'ml-auto max-w-[85%] border-primary/30 bg-primary/10 text-foreground'
                  }`}
                >
                  <p className="mb-2 text-xs uppercase tracking-wide text-muted-foreground">
                    {message.role === 'assistant' ? 'Congenial' : 'You'}
                  </p>
                  <p className="whitespace-pre-wrap text-sm leading-relaxed sm:text-base">
                    {message.content}
                  </p>
                </article>
              ))}
              {isAssistantTyping && (
                <p className="text-xs uppercase tracking-wide text-muted-foreground">
                  Congenial is composing...
                </p>
              )}
              <div ref={conversationEndRef} />
            </div>

            <div className="mt-4 rounded-xl border border-border/60 bg-card/90 p-3 sm:p-4">
              <label htmlFor="chatInput" className="sr-only">
                Message input
              </label>
              <textarea
                id="chatInput"
                value={draft}
                onChange={(event) => setDraft(event.target.value)}
                onKeyDown={onTextareaKeyDown}
                placeholder={CHAT_COPY.placeholder}
                className="h-24 w-full resize-none bg-transparent text-sm leading-relaxed text-foreground outline-none placeholder:text-muted-foreground sm:text-base"
              />
              <div className="mt-3 flex items-center justify-between gap-3">
                <p className="text-xs text-muted-foreground">
                  Not a real AI. (You didn&apos;t think I&apos;d go that far did
                  you??)
                </p>
                <Button onClick={sendMessage} className="gap-2">
                  {CHAT_COPY.ctaLabel}
                  <ArrowUpRight className="h-4 w-4" />
                </Button>
              </div>
              {warning && (
                <p className="mt-2 text-sm text-destructive">{warning}</p>
              )}
            </div>
          </section>
        )}
      </div>
    </main>
  )
}
